[tool.poetry]
name = "script-py"
version = "0.1.0"
description = ""
authors = ["dengxiaojun <dxj1718874198@gmail.com>"]

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"

[tool.poetry.dependencies]
python = "^3.12.7"
PyYAML = "^6.0.3"
plotly = "^6.3.1"
pandas = "^2.3.3"
xlrd = "^2.0.2"
lzstring = "^1.0.4"
fuzzywuzzy = "^0.18.0"
tqdm = "^4.67.1"
python-levenshtein = "^0.27.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
script-py = "script_py.Application:Application.run"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
